folder_experiment: runs/appl_ald_data/plasma/proteinGroups
fn_rawfile_metadata: 'data/single_datasets/raw_meta.csv'
covar: 
  kleiner: age,bmi,gender_num,nas_steatosis_ordinal,abstinent_num
  inflammation: age,bmi,gender_num,nas_steatosis_ordinal,abstinent_num
  steatosis: age,bmi,gender_num,abstinent_num,kleiner,nas_inflam
cutoffs:
  kleiner: 2
  inflammation: 2
  steatosis: 1
disease_ontology: # code from https://disease-ontology.org/
  kleiner: 5082 # liver cirrhosis
  inflammation: 9452 #fatty liver disease
  steatosis: 9452 #fatty liver disease
f_annotations: data/single_datasets/ald_plasma_proteinGroups_annotations.csv # snakemake -> copy to experiment folder
annotaitons_gene_col: PG.Genes