config_split: config/appl_ald_data/plasma/proteinGroups/split.yaml
config_train: config/appl_ald_data/plasma/proteinGroups/train.yaml
folder_experiment: runs/appl_ald_data/plasma/proteinGroups
fn_rawfile_metadata: 'data/ALD_study/processed/raw_meta.csv'