# config for Snakefile_v1
config_split: config/appl_ald_data/plasma/proteinGroups/split.yaml
config_train: config/appl_ald_data/plasma/proteinGroups/train_{model}.yaml
folder_experiment: runs/appl_ald_data_2023_11/plasma/proteinGroups
fn_rawfile_metadata: data/ALD_study/processed/ald_metadata_cli.csv
file_format: pkl
models:
  - RSN
  - Median # maps to median on file system?
  - CF
  - DAE
  - VAE
  - KNN
NAGuideR_methods:
  - BPCA
  - COLMEDIAN
  - GSIMP
  - IMPSEQ
  - IMPSEQROB
  - IRM
  - KNN_IMPUTE
  - LLS
  # - MICE-CART # stopped after 24h
  # - MICE-NORM # stopped after 24h
  - MINDET
  - MINIMUM
  - MINPROB
  - MLE
  - MSIMPUTE
  - MSIMPUTE_MNAR
  - PI
  - QRILC
  - RF
  - ROWMEDIAN
  # - SEQKNN # Error in x[od, ismiss, drop = FALSE]: subscript out of bounds
  - SVDMETHOD
  - TRKNN
  - ZERO
