FN_INTENSITIES: data/ALD_study/processed/ald_plasma_proteinGroups_unfiltered.pkl
FOLDER_EXPERIMENT: runs/data_exploration/ALD_study/plasema_proteinGroups
LOG_TRANSFORM: True
LONG_FORMAT: False
PG_SEPARATOR: ;
