# Dev Environment
name: vaep
channels:
  - pytorch
  - conda-forge
  - base
dependencies:
  - python=3.8.*
  - numpy=1.18.*
  - pandas=1.*
  - ipykernel=5.1.*
  - ipython
  - ipywidgets
  - matplotlib
  - seaborn
  - pip
  # - pytorch
  - scikit-learn
  # - torchvision 
  # - cudatoolkit=10.1
  - tqdm
  - xmltodict
  - openpyxl
  - pip:
    - -e .