# Dev Environment
name: vaep
channels:
  # - defaults
  - conda-forge
  - bioconda
  - pytorch
  - fastai
  - plotly
dependencies:
  - python=3.8
  - numpy
  - pandas=1
  - scipy
  # plotting
  - matplotlib
  - python-kaleido
  - plotly
  - seaborn
  - pip
  # ML
  - pytorch=1
  - scikit-learn=1
  - fastai
  # - torchvision
  - cudatoolkit
  # - tensorboard
  - umap-learn
  # stats
  - pingouin
  - statsmodels
  # other
  - tqdm # progress bars
  - xmltodict # configs
  - openpyxl # xml
  - omegaconf
  # snakemake
  - snakemake-minimal<7.26
  # jupyter
  - jupyterlab # standalone jupyter installation
  - jupyter_contrib_nbextensions # needed to avoid error when exporting to html
  - jupyter-dash
  - papermill # execute ipynb's
  # R packages (listed in NAGuideR)
  - r-base=3.6
  - r-irkernel  
  - r-reshape2
  - r-stringi # + rmarkdown hack for reshape2
  - r-stringr # reshape2
  # - r-gdata
  # - r-glmnet
  - r-e1071
  - r-norm
  - r-missforest
  - r-vim
  - r-mice
  # - r-tidyverse
  - r-readr
  - r-tibble
  # - r-imputelcmd # bioconda
  # - bioconductor-impute # not available for Windows
  # - bioconductor-pcamethods # not available for Windows
  # - rrcovNA, GMSimpute
  # SeqKnn, pcaMethods, DreamAI # bioconductor
  # dev
  # - pytest
  # - pytest-cov
  # - jupytext
  # - jupyterlab_code_formatter
  # - jupyterlab-git
  - pip:
    - -e .
    - mrmr-selection
    