# Dev Environment
name: vaep
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.*
  - numpy=1.20*
  - pandas=1.2
  - ipykernel=5.3.*
  - ipython=7.22.*
  - ipywidgets=7.6.*
  - matplotlib=3.3.*
  - scipy=1.6.*
  - seaborn
  - pip
  - pytorch=1.10.*
  - scikit-learn=1.0.*
  - torchvision
  - cudatoolkit=10.2
  - tensorboard
  - tqdm
  - xmltodict
  - openpyxl
  - pandas-profiling
  - pip:
    - -e .