# Dev Environment
name: vaep
channel:
  - base
  - pytorch
dependencies:
  - python=3.8.*
  - numpy=1.18.*
  - pandas=1.*
  - ipykernel=5.1.*
  - ipywidgets
  - matplotlib
  - seaborn
  - pip
  - pytorch
  # - torchvision 
  - cudatoolkit=10.1
  - tqdm
  - pip:
    - xmltodict
    - -e .