# Dev Environment
name: vaep
channels:
  - defaults
  - pytorch
  - fastai
  - plotly
  - conda-forge
  - bioconda
dependencies:
  - biopython # Aligner
  - python=3.8
  - numpy=1.20
  - pandas>=1.4
  - pandas-profiling
  - scipy>=1.6
  # plotting
  - matplotlib=3.3
  - python-kaleido
  - plotly
  - seaborn
  - pip
  # ML
  - pytorch=1.10.*
  - scikit-learn=1.0.*
  - fastai
  - torchvision
  - cudatoolkit=10.2
  - tensorboard
  - umap-learn
  # stats
  - pingouin
  - statsmodels
  # other
  - tqdm # progress bars
  - xmltodict # configs
  - openpyxl # xml
  - omegaconf
  # snakemake
  - snakemake-minimal=7.12.0
  # jupyter
  - ipykernel=5.3
  - ipython=7.22
  - ipywidgets=7.6
  - jupytext
  - jupyterlab # standalone jupyter installation
  - jupyterlab_code_formatter
  - jupyterlab-git
  - jupyter-dash
  - papermill # execute ipynb's
  # dev
  - pytest
  - pytest-cov
  - jupytext
  - pip:
    - -e .
    - mrmr-selection
    # - git+https://github.com/smazzanti/mrmr.git
    