# Dev Environment
name: vaep
channels:
  - pytorch
  - fastai
  - defaults
  - conda-forge
dependencies:
  - python=3.8.*
  - numpy=1.18.*
  - pandas=1.*
  - ipykernel=5.3.*
  - ipython
  - ipywidgets
  - matplotlib
  - seaborn
  - pip
  - pytorch
  - fastai
  - scikit-learn
  - torchvision
  - cudatoolkit=10.2
  - tensorboard
  - tqdm
  - xmltodict
  - openpyxl
  - papermill
  - pip:
    - -e .