FN_INTENSITIES: data/dev_datasets/df_intensities_evidence_long/Q_Exactive_HF_X_Orbitrap_6070.pkl
fn_rawfile_metadata: data/dev_datasets/df_intensities_evidence_long/metadata.csv
sample_completeness: 0.5
column_names: null