FN_INTENSITIES: data/dev_datasets/df_intensities_proteinGroups_long/Q_Exactive_HF_X_Orbitrap_6070.pkl
FOLDER_EXPERIMENT: runs/knn_comparison/hela_pgs_large
N_FIRST_ROWS:
LOG_TRANSFORM: True
INDEX_COL:
  - 0
  - 1
LONG_FORMAT: True
COMPLETENESS_OVER_SAMPLES: 0.25
MIN_FEAT_PER_SAMPLE: 0.4
PG_SEPARATOR: ;
