FN_INTENSITIES: data/ALD_study/processed/ald_plasma_proteinGroups_80perc_25MNAR.pkl
fn_rawfile_metadata: data/ALD_study/processed/raw_meta.csv
sample_completeness: 0.3
column_names:
  - PG.ProteinAccessions
frac_mnar: 0.25
