FN_INTENSITIES: 'data/single_datasets/df_intensities_evidence_long_2017_2018_2019_2020_N05015_M49321/Q_Exactive_HF_X_Orbitrap_Exactive_Series_slot_#6070.pkl'
fn_rawfile_metadata: 'data/files_selected_metadata.csv'
sample_completeness: 0.5
min_RT_time: 120
select_N: 50