FN_INTENSITIES: 'data/dev_datasets/df_intensities_proteinGroups_long/Q_Exactive_HF_X_Orbitrap_6070.pkl'
fn_rawfile_metadata: 'data/files_selected_metadata.csv'
sample_completeness: 0.5
min_RT_time: 120
select_N: 50