# config for Snakefile_v1
config_split: config/single_dev_dataset/evidence/split.yaml
config_train: config/single_dev_dataset/evidence/train_{model}.yaml
folder_experiment: runs/dev_dataset_large/evidence
fn_rawfile_metadata: data/dev_datasets/df_intensities_evidence_long/metadata.csv
cuda: False
models:
  - Median
  - CF
  - DAE
  - VAE
  - KNN
NAGuideR_methods:
  # - BPCA # stopped after 24h
  - COLMEDIAN
  - IMPSEQ
  - IMPSEQROB
  # - IRM # stopped after 24h
  - KNN_IMPUTE
  # - LLS # error
  # - MICE-CART # stopped after 24h
  # - MICE-NORM # stopped after 24h
  - MINDET
  - MINIMUM
  - MINPROB
  - MLE
  - MSIMPUTE
  - PI
  - QRILC
  # - RF # stopped after 24h
  - ROWMEDIAN
  # - SEQKNN # error: Error in x[od, ismiss, drop = FALSE]: subscript out of bounds
  - SVDMETHOD
  # - TRKNN # stopped after 24h
  - ZERO
