config_split: config/single_dev_dataset/evidence/split.yaml
config_train: config/single_dev_dataset/evidence/train_{model}.yaml
folder_experiment: runs/dev_dataset_large/evidence
fn_rawfile_metadata: data/dev_datasets/df_intensities_evidence_long/metadata.csv
cuda: False
models:
 - Median
 - CF
 - DAE
 - VAE
 - KNN
NAGuideR_methods:
 - ZERO
 - MINIMUM
 - COLMEDIAN
 - ROWMEDIAN
 - KNN_IMPUTE
 # - SEQKNN # error
 # - BPCA # stopped after 30mins
 # - SVDMETHOD # stopped after 30mins
 # - LLS # stopped after 30mins
 # - MLE # error
 - QRILC
 - MINDET
 - MINPROB
 # - IRM # stopped after 30mins
 # - IMPSEQ # error
 # - IMPSEQROB # error
 # - MICE-NORM # stopped after 30mins
 # - MICE-CART # stopped after 30mins
 # - TRKNN # error
 # - RF # stopped after 30mins
 - PI
