# config for Snakefile_v1
config_split: config/single_dev_dataset/example/split.yaml
config_train: config/single_dev_dataset/example/train_{model}.yaml
folder_experiment: runs/example
# folder_experiment: runs/dev_dataset_small/proteinGroups_N50
fn_rawfile_metadata: data/dev_datasets/HeLa_6070/files_selected_metadata_N50.csv
file_format: csv
models:
  - Median # maps to median on file system?
  - CF
  - DAE
  - VAE
  - KNN
NAGuideR_methods:
  - ROWMEDIAN # e1071
  - KNN_IMPUTE # impute
  - SEQKNN # SeqKNN
  - RF # missForest - ~7mins
  - IMPSEQ # rrcovNA
  - QRILC # imputeLCMD
  - SVDMETHOD # pcaMethods
  - MICE-NORM # mice
  - MLE # norm
  - IRM # VIM - ~9mins
  - TRKNN
  - MSIMPUTE # MSIMPUTE_MNAR is slower
  # - GSIMP # slow even on data with fewer features (~44mins)
