config_split: config/single_dev_dataset/peptides/split.yaml
config_train: config/single_dev_dataset/peptides/train_{model}.yaml
folder_experiment: runs/dev_dataset_large/peptides
fn_rawfile_metadata: data/dev_datasets/df_intensities_peptides_long/metadata.csv
cuda: False
models:
 - Median # ~ 1:20 min
 - CF # ~ 12:07 min
 - DAE # 4:36 mins
 - VAE #  ~ 3:32 min
 - KNN  # ~ 2:20 min
NAGuideR_methods:
 - ZERO
 - MINIMUM
 - COLMEDIAN
 - ROWMEDIAN
 - KNN_IMPUTE
 # - SEQKNN # error
 # - BPCA # stopped after 30mins
 # - SVDMETHOD # stopped after 30mins
 # - LLS # stopped after 30mins
 # - MLE # error
 - QRILC
 - MINDET
 - MINPROB
 # - IRM # stopped after 30mins
 # - IMPSEQ # error
 # - IMPSEQROB # error
 # - MICE-NORM # stopped after 30mins
 # - MICE-CART # stopped after 30mins
 # - TRKNN # error
 # - RF # stopped after 30mins
 - PI
