config_split: config/single_dev_dataset/peptides/split.yaml
config_train: config/single_dev_dataset/peptides/train_{model}.yaml
folder_experiment: runs/Q_Exactive_HF_X_Orbitrap_6070/peptides
fn_rawfile_metadata: data/dev_datasets/df_intensities_peptides_long/metadata.csv
models:
 - Median # ~ 1:20 min
 - CF # ~ 12:07 min
 - DAE # 4:36 mins
 - VAE #  ~ 3:32 min
 - KNN  # ~ 2:20 min
NAGuideR_methods:
  # - lls # takes long
  - knnmethod # 1:44 min
  # - seqknn # error
  # - rf # takes long
  # - impseq
  - qrilc # ~ 1 min
  - minprob # ~ 10 sec
  - mindet # ~ 10 sec
  # - seqknn
  # - svdmethod

