# config for Snakefile_v1
config_split: config/single_dev_dataset/peptides_N50/split.yaml
config_train: config/single_dev_dataset/peptides_N50/train_{model}.yaml
folder_experiment: runs/dev_dataset_small/peptides_N50
fn_rawfile_metadata: data/dev_datasets/df_intensities_peptides_long/metadata.csv
cuda: False
file_format: csv
models:
  - Median # maps to median on file system?
  - CF # 3min
  - DAE # 3min
  - VAE # 5min
  - KNN
NAGuideR_methods:
 - BPCA #27min
 - COLMEDIAN
 - IMPSEQ
 - IMPSEQROB
 - IRM # 8h55min
 - KNN_IMPUTE
 - LLS # 10h21min
 - MICE-CART # 2h20min
 - MICE-NORM # 4h25min
 - MINDET
 - MINIMUM
 - MINPROB
 - MLE
 - MSIMPUTE
 - PI
 - QRILC
 - RF # 5h38min
 - ROWMEDIAN
 - SEQKNN # 17min
 - SVDMETHOD
 - TRKNN #4h15min
 - ZERO