config_split: config/single_dev_dataset/peptides_N50/split.yaml
config_train: config/single_dev_dataset/peptides_N50/train_{model}.yaml
folder_experiment: runs/dev_dataset_small/peptides_N50
fn_rawfile_metadata: data/dev_datasets/df_intensities_peptides_long/metadata.csv
cuda: False
file_format: csv
models:
  - Median # maps to median on file system?
  - CF
  - DAE
  - VAE
  - KNN
NAGuideR_methods:
 - BPCA
 - COLMEDIAN
 - IMPSEQ
 - IMPSEQROB
 - IRM
 - KNN_IMPUTE
 - LLS
 - MICE-CART # stopped after 24h
 - MICE-NORM # stopped after 24h
 - MINDET
 - MINIMUM
 - MINPROB
 - MLE
 - MSIMPUTE
 - PI
 - QRILC
 - RF
 - ROWMEDIAN
 - SEQKNN
 - SVDMETHOD
 - TRKNN
 - ZERO