config_split: config/single_dev_dataset/proteinGroups/split.yaml
config_train: config/single_dev_dataset/proteinGroups/train_{model}.yaml
folder_experiment: runs/dev_dataset_large/proteinGroups
fn_rawfile_metadata: data/dev_datasets/df_intensities_proteinGroups_long/metadata.csv
cuda: True
models:
 - Median
 - CF
 - DAE
 - VAE
 - KNN
NAGuideR_methods:
 - ZERO
 - MINIMUM
 - COLMEDIAN
 - ROWMEDIAN
 - KNN_IMPUTE
 # - SEQKNN # error
 # - BPCA # stopped after 30mins
 - SVDMETHOD # stopped after 30mins
 - LLS
 # - MLE # error
 - QRILC
 - MINDET
 - MINPROB
 # - IRM # stopped after 30mins
 # - IMPSEQ # error
 # - IMPSEQROB # error
 # - MICE-NORM # stopped after 30mins
 # - MICE-CART # stopped after 30mins
 # - TRKNN # error
 - RF
 - PI