config_split: config/single_dev_dataset/proteinGroups/split.yaml
config_train: config/single_dev_dataset/proteinGroups/train_{model}.yaml
folder_experiment: runs/Q_Exactive_HF_X_Orbitrap_6070/proteinGroups
fn_rawfile_metadata: data/dev_datasets/df_intensities_proteinGroups_long/metadata.csv
cuda: True
models:
 - Median
 - CF
 - DAE
 - VAE
 - KNN
NAGuideR_methods:
  - lls
  - knnmethod
  - rf
  # - impseq # fails