# config for Snakefile_v1
config_split: config/single_dev_dataset/proteinGroups/split.yaml
config_train: config/single_dev_dataset/proteinGroups/train_{model}.yaml
folder_experiment: runs/dev_dataset_large/proteinGroups
fn_rawfile_metadata: data/dev_datasets/df_intensities_proteinGroups_long/metadata.csv
cuda: False
models:
 - Median
 - CF  # 2min
 - DAE # 2min
 - VAE # 2min
 - KNN
NAGuideR_methods:
 - BPCA #6h41min
 - COLMEDIAN
 - IMPSEQ # 1min
 - IMPSEQROB
 - IRM # 7h52min
 - KNN_IMPUTE
 - LLS
 # - MICE-CART # stopped after 24h
 # - MICE-NORM # stopped after 24h
 - MINDET
 - MINIMUM
 - MINPROB
 - MLE
 - MSIMPUTE
 - PI
 - QRILC
 - RF # 58min
 - ROWMEDIAN
 # - SEQKNN # Error in x[od, ismiss, drop = FALSE]: subscript out of bounds
 - SVDMETHOD # 16min
 - TRKNN # 5h38min
 - ZERO