config_split: config/single_dev_dataset/proteinGroups/split.yaml
config_train: config/single_dev_dataset/proteinGroups/train_{model}.yaml
folder_experiment: runs/dev_dataset_large/proteinGroups
fn_rawfile_metadata: data/dev_datasets/df_intensities_proteinGroups_long/metadata.csv
cuda: False
models:
 - Median
 - CF
 - DAE
 - VAE
 - KNN
NAGuideR_methods:
 - BPCA
 - COLMEDIAN
 - IMPSEQ
 - IMPSEQROB
 - IRM
 - KNN_IMPUTE
 - LLS
 - MICE-CART # stopped after 24h
 - MICE-NORM # stopped after 24h
 - MINDET
 - MINIMUM
 - MINPROB
 - MLE
 - MSIMPUTE
 - PI
 - QRILC
 - RF
 - ROWMEDIAN
 - SEQKNN
 - SVDMETHOD
 - TRKNN
 - ZERO