# config for Snakefile_v2.smk
config_split: runs/mnar_mcar/pg_l_50MNAR/01_0_split_data.yaml # ! will be build
config_train: runs/mnar_mcar/pg_l_50MNAR/train_{model}.yaml # ! will be build, should say model_key next
folder_experiment: runs/mnar_mcar/pg_l_50MNAR
frac_mnar: 0.5
fn_rawfile_metadata: data/dev_datasets/df_intensities_peptides_long/metadata.csv
file_format: csv
split_data:
        FN_INTENSITIES: data/dev_datasets/df_intensities_evidence_long/Q_Exactive_HF_X_Orbitrap_6070.pkl
        sample_completeness: 0.4
        feat_prevalence: 0.25
        index_col: 0
        meta_date_col: Content Creation Date
        column_names: null
models:
        - Median:
                  model: Median # needs to set at least one parameter
        - CF:
                  model: CF
                  file_format: csv
                  latent_dim: 50
                  batch_size: 4096
                  epochs_max: 30
                  sample_idx_position: 0
                  cuda: False
                  save_pred_real_na: True
        - DAE:
                  model: DAE
                  file_format: csv
                  latent_dim: 50
                  batch_size: 10
                  epochs_max: 200
                  hidden_layers: "512"
                  sample_idx_position: 0
                  cuda: False
                  save_pred_real_na: True
        - VAE:
                  model: VAE
                  file_format: csv
                  latent_dim: 25
                  batch_size: 10
                  epochs_max: 200
                  hidden_layers: "512"
                  sample_idx_position: 0
                  cuda: False
                  save_pred_real_na: True
        - KNN:
                  model: KNN
                  neighbors: 3
                  file_format: csv
NAGuideR_methods:
        # - BPCA # > 24h, killed
        - COLMEDIAN
        # - GSIMP # > 24h, killed
        - IMPSEQ
        - IMPSEQROB
        # - IRM # > 24h, killed
        - KNN_IMPUTE
        # - LLS # Error in svd(X): infinite or missing values in 'x'
        # - MICE-CART # > 24h, killed
        # - MICE-NORM # > 24h, killed
        - MINDET
        - MINIMUM
        - MINPROB
        - MLE
        - MSIMPUTE
        - MSIMPUTE_MNAR
        - PI
        - QRILC
        # - RF # > 24h, killed
        - ROWMEDIAN
        # - SEQKNN # error
        - SVDMETHOD
        # - TRKNN # 24h, killed
        - ZERO
