# config for Snakefile_v2
config_split: runs/mnar_mcar/pg_l_50MNAR/01_0_split_data.yaml # ! will be build
config_train: runs/mnar_mcar/pg_l_50MNAR/train_{model}.yaml # ! will be build, should say model_key next
folder_experiment: runs/mnar_mcar/pg_l_50MNAR
frac_mnar: 0.5
fn_rawfile_metadata: data/dev_datasets/df_intensities_proteinGroups_long/metadata.csv
cuda: False
file_format: csv
split_data:
    FN_INTENSITIES: data/dev_datasets/df_intensities_proteinGroups_long/Q_Exactive_HF_X_Orbitrap_6070.pkl
    sample_completeness: 0.4
    feat_prevalence: 0.25
    index_col: 0
    meta_date_col: Content Creation Date
models:
    - Median:
          model: Median
    - CF: # 2min
          model: CF
          latent_dim: 50
          batch_size: 32768
          epochs_max: 100
          sample_idx_position: 0
          cuda: False
          save_pred_real_na: True
    - DAE: # 2min
          model: DAE
          latent_dim: 25
          batch_size: 64
          epochs_max: 100
          hidden_layers: "512"
          sample_idx_position: 0
          cuda: False
          save_pred_real_na: True
    - VAE: # 2min
          model: VAE
          latent_dim: 25
          batch_size: 64
          epochs_max: 50
          hidden_layers: "512"
          sample_idx_position: 0
          cuda: False
          save_pred_real_na: True
    - KNN:
          model: KNN
          neighbors: 3
          file_format: csv
NAGuideR_methods:
    - BPCA #6h41min
    - COLMEDIAN
    # - GSIMP # stopped after 24h
    - IMPSEQ # 1min
    - IMPSEQROB
    - IRM # 7h52min
    - KNN_IMPUTE
    - LLS
    # - MICE-CART # stopped after 24h
    # - MICE-NORM # stopped after 24h
    - MINDET
    - MINIMUM
    - MINPROB
    - MLE
    - MSIMPUTE
    - MSIMPUTE_MNAR
    - PI
    - QRILC
    - RF # 58min
    - ROWMEDIAN
    # - SEQKNN # Error in x[od, ismiss, drop = FALSE]: subscript out of bounds
    - SVDMETHOD # 16min
    - TRKNN # 5h38min
    - ZERO
