config_split: config/single_dev_dataset/evidence_N50/split.yaml
config_train: config/single_dev_dataset/evidence_N50/train_{model}.yaml
folder_experiment: runs/dev_dataset_small/evidence_N50
fn_rawfile_metadata: data/dev_datasets/df_intensities_evidence_long/metadata.csv
file_format: csv
models:
  - Median
  - CF
  - DAE
  - VAE
  - KNN
NAGuideR_methods:
  - BPCA
  - COLMEDIAN
  - IMPSEQ
  - IMPSEQROB
  - IRM # stopped after 24h
  - KNN_IMPUTE
  - LLS # stopped after 24h
  - MICE-CART
  - MICE-NORM
  - MINDET
  - MINIMUM
  - MINPROB
  - MLE
  - MSIMPUTE
  - PI
  - QRILC
  - RF # stopped after 24h
  - ROWMEDIAN
  - SEQKNN
  - SVDMETHOD
  - TRKNN # stopped after 24h
  - ZERO