# config for Snakefile_v2.smk
config_split: runs/alzheimer_study_2023_11_v2/split.yaml # ! will be build
config_train: runs/alzheimer_study_2023_11_v2/train_{model}.yaml # ! will be build
folder_experiment: runs/alzheimer_study_2023_11_v2
fn_rawfile_metadata: https://raw.githubusercontent.com/RasmussenLab/njab/HEAD/docs/tutorial/data/alzheimer/meta.csv
cuda: False
file_format: csv
split_data:
    FN_INTENSITIES: https://raw.githubusercontent.com/RasmussenLab/njab/HEAD/docs/tutorial/data/alzheimer/proteome.csv
    sample_completeness: 0.5
    feat_prevalence: 0.25
    column_names:
        - protein groups
    index_col: 0
    meta_cat_col: _collection site
    meta_date_col: null
    frac_mnar: 0.25
    frac_non_train: 0.1
models:
    - Median:
          model: Median
    - CF:
          model: CF
          latent_dim: 50
          batch_size: 1024
          epochs_max: 100
          sample_idx_position: 0
          cuda: False
          save_pred_real_na: True
    - DAE:
          model: DAE
          latent_dim: 10
          batch_size: 64
          epochs_max: 300
          hidden_layers: "64"
          sample_idx_position: 0
          cuda: False
          save_pred_real_na: True
    - VAE:
          model: VAE
          latent_dim: 10
          batch_size: 64
          epochs_max: 300
          hidden_layers: "64"
          sample_idx_position: 0
          cuda: False
          save_pred_real_na: True
    - KNN:
          model: KNN
          neighbors: 3
          file_format: csv
NAGuideR_methods:
    - BPCA
    - COLMEDIAN
    - IMPSEQ
    - IMPSEQROB
    - IRM
    - KNN_IMPUTE
    - LLS
    - MICE-CART
    - MICE-NORM
    - MINDET
    - MINIMUM
    - MINPROB
    - MLE
    - MSIMPUTE
    - MSIMPUTE_MNAR
    - PI
    - QRILC
    - RF
    - ROWMEDIAN
    # - SEQKNN # Error in x[od, ismiss, drop = FALSE]: subscript out of bounds
    - SVDMETHOD
    - TRKNN
    - ZERO
