# runs in ~30 mins
epochs_max:
- 15
batch_size: 64
batch_size_collab: 32768
hidden_layers:
- '512'
- '256_128'
latent_dim:
- 50
folder_grid_search: "runs/optimize"
folder_experiment2: "runs/optimize/{{level}}"
folder_experiment: "runs/optimize/{level}"
fn_rawfile_metadata: data/dev_datasets/df_intensities_proteinGroups_long/metadata.csv # global metadata file... 
levels:
- proteinGroups
# - aggPeptides
# - evidence 
config_split: 'config/single_dev_dataset/{level}/split.yaml'
config_train: 'placeholder.yaml'
cuda: True
models:
  - CF
  - DAE
  - VAE
  - median