batch_size:
- 32
- 64
epochs:
- 30
hidden_layers:
- 1
- 2
- 3
- 4
latent_dim:
- 10
- 25
- 50
- 75
- 100
folder_experiment: "runs/grid_search/proteinGroups"
config_split: 'proteinGroups.yaml'
config_train: 'placeholder.yaml'
name_template: run_HL_{hidden_layers}_LD_{latent_dim}_E_{epochs}_BS_{batch_size}