epochs:
- 100
hidden_layers:
- '1024_512'
- '512_256'
- '512_256_128'
- '1024_512_256'
- '2056_1024_512'
- '2056_1024_512_256'
latent_dim:
- 10
- 25
- 50
- 75
- 100
folder_experiment: "runs/grid_search/evidence"
config_split: 'config/evidence_split.yaml'
config_train: 'placeholder.yaml'
name_template: run_LD_{latent_dim}_E_{epochs}