epochs:
- 100
hidden_layers:
# - 1
- 2
- 3
- 4
- '1024_512_256'
latent_dim:
- 10
- 25
- 50
- 75
- 100
folder_experiment: "runs/grid_search/proteinGroups"
config_split: 'proteinGroups.yaml'
config_train: 'placeholder.yaml'
name_template: run_LD_{latent_dim}_HL_{hidden_layers}_E_{epochs}