epochs:
- 100
hidden_layers:
- '256'
- '512'
- '256_128'
- '512_256'
- '512_256_128'
- '1024_512_256'
- '128_128_128'
- '256_256_128_128'
latent_dim:
- 10
- 25
- 50
- 75
- 100
folder_experiment: "runs/grid_search/proteinGroups"
config_split: 'config/proteinGroups_split.yaml'
config_train: 'placeholder.yaml'
name_template: run_LD_{latent_dim}_E_{epochs}