# models_training:
folder_experiment:  'runs/experiment_03/df_intensities_proteinGroups_long_2017_2018_2019_2020_N05015_M04547/Q_Exactive_HF_X_Orbitrap_Exactive_Series_slot_#6070'
file_format: pkl
latent_dim: 50
hidden_layers: "512"
sample_idx_position: 0
