epochs_max:
- 100
batch_size: 64
repeats: 5
folder: "runs/repeat_best"
levels:
- proteinGroups
- aggPeptides
- evidence 
fn_rawfile_metadata: data/files_selected_metadata.csv
config_split: 'config/single_dev_dataset/{level}/split.yaml'
config_train: 'config/single_dev_dataset/{level}/train.yaml'
repitition_name: 'repeat'
