# Build in Snakemake workflow
FN_INTENSITIES: data/dev_datasets/HeLa_6070/protein_groups_wide_N50.csv
fn_rawfile_metadata: data/dev_datasets/HeLa_6070/files_selected_metadata_N50.csv
sample_completeness: 0.5
column_names:
- Gene Names
index_col: 0
meta_date_col: Content Creation Date
frac_mnar: 0.25
frac_non_train: 0.1
