name: Test that tutorial runs on latest colab image

on:
    # push:
    #     branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: '0 2 3 * *'

jobs:
    test-tutorial-on-colab:
        name: Test tutorial on latest colab image
        runs-on: ubuntu-latest-4core # increase disk space  
        # https://console.cloud.google.com/artifacts/docker/colab-images/europe/public/runtime
        container:
            image: europe-docker.pkg.dev/colab-images/public/runtime:latest
        defaults:
          run:
            shell: bash -el {0}
        steps:
        - uses: actions/checkout@v4
        - name: Install pimms-learn (from branch) and papermill
          if: github.event_name == 'pull_request'
          run: | 
            pip install --user .
            pip install papermill
            which papermill
            cd project
            python3 -c "import pimmslearn; print(pimmslearn.__version__)"
            python3 -c "import pimmslearn; pimmslearn.io"
            python3 -c "import pimmslearn.io"
            python -m papermill 04_1_train_pimms_models.ipynb 04_1_train_pimms_models_output.ipynb
            papermill 04_1_train_pimms_models.ipynb 04_1_train_pimms_models_output.ipynb
        - name: Install pimms-learn (from PyPI) and papermill
          if: github.event_name == 'schedule'
          run: | 
            pip install pimms-learn papermill
        - name: Run tutorial
          run: |
            cd project
            which papermill
            papermill 04_1_train_pimms_models.ipynb 04_1_train_pimms_models_output.ipynb
            papermill 04_1_train_pimms_models.ipynb 04_1_train_pimms_models_no_val.ipynb -p sample_splits False

